# Used in development

version: "2"
services:
  frontend:
    image: "node:hydrogen-alpine"
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app/apps/frontend"
    command: "npm run dev -- --host"
    ports:
      - "3000:3000"
    environment:
      - VITE_API_ENDPOINT=http://localhost:8080
      - VITE_OAUTH_CLIENT_ID=953907026294-3ev1hl5pqitqkks4alkkqhs5616oidq7.apps.googleusercontent.com
  
  backend:
    image: "node:hydrogen-alpine"
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app/apps/backend"
    command: "npm run dev"
    depends_on:
      scylla:
        condition: service_healthy
      redis:
        condition: service_started
      function:
        condition: service_started
    ports:
      - "8080:8080"
    env_file:
      - "global.env"
    environment:
      - MODE=development
      - PORT=8080
      - DB_HOST=scylla
      - DB_PORT=9042
      - DB_KEYSPACE=kontestis
      - DB_DATACENTER=datacenter1
      - REDIS_URL=redis://redis:6379
      - OAUTH_CLIENT_ID=953907026294-3ev1hl5pqitqkks4alkkqhs5616oidq7.apps.googleusercontent.com
      - OAUTH_ALLOWED_DOMAINS=skole.hr,hm4.dev
      - EVALUATOR_ENDPOINT=http://function:8080

  function:
    build:
      context: ./apps/function
      dockerfile: base.dockerfile
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app/apps/function"
    command: "npm run dev"
    ports:
      - 8081:8080

  scylla:
    image: "scylladb/scylla:5.1.7"
    command: "--smp 1 --skip-wait-for-gossip-to-settle 0"
    ports:
      - "9042:9042"
    volumes:
      - "./tools/scylla:/var/lib/scylla"
    healthcheck:
      test: cqlsh -e "exit"
      interval: 2s
      retries: 10
      start_period: 10s
      timeout: 10s

  redis:
    image: "redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"


  influxdb:
    image: influxdb:2.6-alpine
    volumes:
      - "./tools/influx:/var/lib/influxdb2"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root1234
      - DOCKER_INFLUXDB_INIT_ORG=kontestis-org
      - DOCKER_INFLUXDB_INIT_BUCKET=kontestis
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=devtoken
    ports:
      - "8086:8086"
