# Used in development

version: "2"
services:
  frontend:
    image: "node:hydrogen-alpine"
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app/apps/frontend"
    command: "npm run dev -- --host"
    ports:
      - "3000:3000"
    environment:
      - VITE_API_ENDPOINT=http://localhost:8080

  backend:
    image: "node:hydrogen-alpine"
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app/apps/backend"
    command: "npm run dev"
    depends_on:
      scylla:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - MODE=development
      - PORT=8080
      - DB_HOST=scylla
      - DB_PORT=9042
      - DB_KEYSPACE=kontestis
      - DB_DATACENTER=datacenter1
      - TOKEN_SECRET=sometokensecret
      - EVALUATOR_ENDPOINT=https://kontestis-evaluator-y7a5esl5qq-oa.a.run.app
      - REDIS_URL=redis://redis:6379

  scylla:
    image: "scylladb/scylla:5.0.5"
    command: "--smp 1 --skip-wait-for-gossip-to-settle 0"
    ports:
      - "9042:9042"
    volumes:
      - "./tools/scylla:/var/lib/scylla"
    healthcheck:
      test: cqlsh -e "exit"
      interval: 2s
      retries: 10
      start_period: 10s
      timeout: 10s

  redis:
    image: "redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

