# Used in development

version: "2"

services:
  backend:
    image: "node:hydrogen-alpine"
    volumes:
      - ".:/app"
    working_dir: "/app"
    command: "npm run dev"
    depends_on:
      - scylla
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=scylla
      - DB_PORT=9042
      - DB_KEYSPACE=kontestis
      - DB_DATACENTER=datacenter1
      - TOKEN_SECRET=sometokensecret

  scylla:
    image: "scylladb/scylla:5.0.5"
    command: "--smp 1 --skip-wait-for-gossip-to-settle 0"
    ports:
      - "9042:9042"
    volumes:
      - "./tools/scylla:/var/lib/scylla"
    logging:
      driver: none

