# Used in development

services:
  frontend:
    image: "node:hydrogen-alpine"
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app/apps/frontend"
    command: "npm run dev -- --host"
    ports:
      - "3000:3000"
    environment:
      - VITE_CAPTCHA_SITE_KEY=6Le6ZrYqAAAAAPG-tsPqZm_1numHrNnJ66Ob9KYU
      - VITE_API_ENDPOINT=http://localhost:8080
      - VITE_OAUTH_CLIENT_ID=953907026294-3ev1hl5pqitqkks4alkkqhs5616oidq7.apps.googleusercontent.com
      - VITE_AAI_EDU_LOGOUT_URL=https://fed-lab.aaiedu.hr/sso/module.php/oidc/logout.php
      - VITE_AAI_EDU_LOGOUT_REDIRECT_URL=http://localhost:3000/

  backend:
    image: "node:hydrogen-alpine"
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app/apps/backend"
    command: "npm run dev"
    depends_on:
      scylla:
        condition: service_healthy
      redis:
        condition: service_started
      function:
        condition: service_started
    ports:
      - "8080:8080"
    env_file:
      - "global.env"
    environment:
      - MODE=development
      - PORT=8080
      - DB_HOST=scylla
      - DB_PORT=9042
      - DB_KEYSPACE=kontestis
      - DB_DATACENTER=datacenter1
      - REDIS_URL=redis://redis:6379
      - INFLUXDB_URL=http://influxdb:8086
      - OAUTH_CLIENT_ID=953907026294-3ev1hl5pqitqkks4alkkqhs5616oidq7.apps.googleusercontent.com
      - EVALUATOR_ENDPOINT=http://function:8080
      - CAPTCHA_DISABLED=true
      - S3_ENDPOINT=minio
      - S3_PORT=9000
      - S3_ACCESS_KEY=root
      - S3_SECRET_KEY=password

  function:
    build:
      context: ./apps/function
      dockerfile: base.dockerfile
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app/apps/function"
    command: "npm run dev"
    ulimits:
      stack:
        soft: 20971520
        hard: 20971520
    ports:
      - 8081:8080

  scylla:
    image: "scylladb/scylla:5.1.7"
    command: "--smp 1 --skip-wait-for-gossip-to-settle 0 --developer-mode 1"
    ports:
      - "9042:9042"
    volumes:
      - "./tools/scylla:/var/lib/scylla"
    healthcheck:
      test: cqlsh -e "exit"
      interval: 2s
      retries: 10
      start_period: 10s
      timeout: 10s

  redis:
    image: "redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"


  influxdb:
    image: influxdb:2.6-alpine
    volumes:
      - "./tools/influx:/var/lib/influxdb2"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root1234
      - DOCKER_INFLUXDB_INIT_ORG=kontestis-org
      - DOCKER_INFLUXDB_INIT_BUCKET=kontestis
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=devtoken
      - TZ=Europe/Zagreb
    ports:
      - "8086:8086"

  minio:
    image: "minio/minio:RELEASE.2025-02-18T16-25-55Z"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./tools/minio:/data
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: root 
      MINIO_ROOT_PASSWORD: password
