name: "Backend auto-deployment"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "🐳 Build"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Docker
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: docker-${{ runner.os }}

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t ghcr.io/itklubbozolagan/kontestis-backend ./apps/backend

      - name: Push image
        run: docker push ghcr.io/itklubbozolagan/kontestis-backend

