name: "Backend auto-deployment"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "🐳 Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: apps/backend
          platforms: linux/amd64
          file: apps/backend/Dockerfile
          tags: ghcr.io/itklubbozolagan/kontestis-backend:latest

