name: "🔎 Dependency mismatch check"

on:
    push:
        branches:
            - "main"
            - "dev"
        paths:
            - "apps/**/package.json"
            - "packages/**/package.json"
            - ".github/workflows/dependency-check.yml"

jobs:
    deploy:
        name: "🔎 Dependency mismatch check"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: 9.7.1

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Install packages
              run: pnpm --filter=@kontestis/scripts... install

            - name: Check mismatched dependencies
              run: pnpm --filter=@kontestis/scripts exec-script dependency-check
