name: "Auto-deployment"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "🐳 Build"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/953907026294/locations/global/workloadIdentityPools/kontestis-actions/providers/kontestis-provider"
          service_account: "github-actions@speedy-baton-368023.iam.gserviceaccount.com"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: eu.gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: Dockerfile
          tags: eu.gcr.io/speedy-baton-368023/kontestis-evaluator
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: "🚚 Release"
    runs-on: ubuntu-latest
    needs: ["build"]
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/953907026294/locations/global/workloadIdentityPools/kontestis-actions/providers/kontestis-provider"
          service_account: "github-actions@speedy-baton-368023.iam.gserviceaccount.com"

      - id: deploy
        name: Deploy to GCP
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: kontestis-evaluator
          image: eu.gcr.io/speedy-baton-368023/kontestis-evaluator
          region: europe-west6

      - name: Display URL
        run: "curl \"${{ steps.deploy.outputs.url }}\""
