name: Deploy to Edgeserver

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: "🚚 Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install PNPM
        uses: pnpm/action-setup@v2
          version: 7.25.0

      - name: Set PNPM store path
        run: "echo \"PNPM_STORE_PATH=$(pnpm store path)\" >> $GITHUB_ENV"

      - name: Cache PNPM packages
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install packages
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Edgeserver Upload
        uses: v3xlabs/edgeserver-upload@master
        with:
          app_id: "138206523384926208"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGESERVER_TOKEN }}
          directory: dist
