name: "🚚 Deploy to Edgeserver"

on:
  push:
    branches:
      - "main"
    paths:
      - "apps/frontend/**"
      - "packages/**"
      - "!packages/scripts/**"
      - ".github/workflows/frontend-deploy.yml"

jobs:
  deploy:
    name: "🚚 Build & Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install packages
        run: pnpm --filter=@kontestis/frontend... install

      - name: Build
        run: pnpm --filter=@kontestis/frontend build

      - name: Edgeserver Upload
        uses: v3xlabs/edgeserver-upload@master
        with:
          app_id: "177185099509403648"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGESERVER_TOKEN }}
          directory: apps/frontend/dist
