name: Deploy to Edgeserver

on:
  push:
    branches:
      - "main"

jobs:
  check:
    name: "🔎 Check"
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: changes
        name: Filter files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - "apps/frontend/**"
              - "pacakges/**"
  deploy:
    name: "🚚 Deploy"
    runs-on: ubuntu-latest
    needs: ["check"]
    if: needs.check.outputs.frontend == 'true'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.0

      - name: Set PNPM store path
        run: "echo \"PNPM_STORE_PATH=$(pnpm store path)\" >> $GITHUB_ENV"

      - name: Cache PNPM packages
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install packages
        run: pnpm --filter=@kontestis/frontend... install

      - name: Build
        run: pnpm --filter=@kontestis/frontend... build

      - name: Edgeserver Upload
        uses: v3xlabs/edgeserver-upload@master
        with:
          app_id: "138206523384926208"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGESERVER_TOKEN }}
          directory: apps/frontend/dist
