name: 🛠 Type-check

on:
    push:
        branches:
            - "main"
            - "dev"
        paths:
            - "**.ts"
            - "**.tsx"
            - ".github/workflows/typecheck.yml"

jobs:
    deploy:
        name: "🛠 Type-check"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: 9.7.1

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Cache tsbuildinfo
              uses: actions/cache@v3
              with:
                  path: "**/tsconfig.tsbuildinfo"
                  key: ${{ runner.os }}-tsbuildinfo

            - name: Install packages
              run: pnpm install

            - name: Typecheck
              run: pnpm typecheck
