name: Typecheck

on:
  push:
    branches:
      - "main"

jobs:
  check:
    name: "🔎 Check"
    runs-on: ubuntu-latest
    outputs:
      typecheck: ${{ steps.changes.outputs.typecheck }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: changes
        name: Filter files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            typecheck:
              - "**.ts"
              - "**.tsx"
  deploy:
    name: "🛠 Typecheck"
    runs-on: ubuntu-latest
    needs: ["check"]
    if: needs.check.outputs.typecheck == 'true'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.0

      - name: Set PNPM store path
        run: "echo \"PNPM_STORE_PATH=$(pnpm store path)\" >> $GITHUB_ENV"

      - name: Cache PNPM packages
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install packages
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

