name: Typecheck

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: "🛠 Typecheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.0

      - name: Set PNPM store path
        run: "echo \"PNPM_STORE_PATH=$(pnpm store path)\" >> $GITHUB_ENV"

      - name: Cache PNPM packages
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install packages
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

